---

- name: Update All
  hosts: Ubuntuservers
  remote_user: sroa
  become: yes

  tasks:
   - name: Update the cache and upgrade all packages
     apt:
       upgrade_cache: yes
       upgrade: full

       # This is a test committing changes from my own branch - SRQ


...
